### ISSUE TITLE
FF1 Bug fixes

### ISSUE THREAD

**Issue by Entroper** [Entroper/FF1Randomizer#1]
One option I'd like to have is to allow the randomizer to patch several bugs in the original game.

Reference (search for SEC9): http://www.gamefaqs.com/nes/522595-final-fantasy/faqs/57009
- [x] HOUSE saves before restoring MP
- [x] Elemental and monster category weapons don't work
- [x] Critical hit chance on weapons doesn't work
- [x] Running not based on Luck+Level
- [x] Enemy status attacks apply to misses after the first hit
- [ ] Enemy magic that hits allies doesn't hit the caster
- [ ] Enemy protection spells don't work (AFIR)
- [ ] Black Belt armor glitch on level up

Lots of magic bugs:
- [x] LOCK
- [x] LOK2
- [x] HEL2
- [x] TMPR
- [x] SABR
- [ ] XFER

**Comment by Entroper** [comment]
Some of the easier ones will make it into 1.1 (the HOUSE thing, almost certainly).

I'm not sure what to do about the run chance.  The game loads the wrong data, which is easy to fix, but then the formula is dumb, too.  Being higher level reduces your chance of running.

**Comment by Entroper** [comment]
This is now top priority with speed hacks working well.

**Comment by Entroper** [comment]
XFER and AFIR: http://www.romhacking.net/forum/index.php?topic=24130.0

**Comment by Kronoan** [comment]
I love the new version Entroper! Keep working on it until you get all of the bugs fixed! I especially want XFER to work properly! :)

**Comment by Entroper** [comment]
I split the remaining items up into separate issues.
