### ISSUE TITLE
Speed hacks

### ISSUE THREAD

**Issue by gameboy9** [Entroper/FF1Randomizer#24]
Feel free to implement as much or as little of these as you want.  :)  The field text window should open a lot faster and the transitions should be almost instantaneous as well as the below.

I'm not sure if all of these are documented properly, so please let me know if you have any questions.

`private void button4_Click(object sender, EventArgs e)
        {
            if (!loadRom())
                return;

            // Double walking speed
            romData[0x3d088] = 0x02;
            romData[0x3d6f7] = romData[0x3d6f8] = romData[0x3d6f9] = 0xea;
            romData[0x3d71c] = romData[0x3d71d] = romData[0x3d71e] = 0xea;
            romData[0x3d956] = 0x60;
            romData[0x3d8e6] = romData[0x3d8e7] = romData[0x3d8e8] = 0xea;
            romData[0x3d630] = 0x08;
            romData[0x3d6a9] = 0x08;
            // Battle speedups
            romData[0x31e2d] = 0x01;
            romData[0x31e92] = 0x01;
            romData[0x31e5c] = 0x01;

            // Inn fade in/out
            romData[0x3ffa3] = romData[0x3ffa4] = romData[0x3ffa5] = 0xea;
            romData[0x3ffb8] = romData[0x3ffb9] = romData[0x3ffba] = 0xea;

            // Speed up character resort
            romData[0x399b7] = romData[0x399b8] = romData[0x399b9] = 0xea;

            romData[0x3795b] = romData[0x3795c] = romData[0x3795d] = 0xea;
            romData[0x37966] = romData[0x37967] = romData[0x37968] = 0xea;
            romData[0x37973] = romData[0x37974] = romData[0x37975] = 0xea;
            romData[0x379a9] = romData[0x379aa] = romData[0x379ab] = 0xea;
            romData[0x379b4] = romData[0x379b5] = romData[0x379b6] = 0xea;
            romData[0x379c1] = romData[0x379c2] = romData[0x379c3] = 0xea;
            romData[0x379fc] = romData[0x379fd] = romData[0x379fe] = 0xea;

            romData[0x35aa5] = romData[0x35aa6] = romData[0x35aa7] = romData[0x35aa8] = 
                romData[0x35aa9] = romData[0x35aaa] = romData[0x35aab] = romData[0x35aac] = 
                romData[0x35aad] = romData[0x35aae] = romData[0x35aaf] = romData[0x35ab0] = 
                romData[0x35ab1] = romData[0x35ab2] = romData[0x35ab3] = romData[0x35ab4] = 
                romData[0x35ab5] = romData[0x35ab6] = romData[0x35ab7] = romData[0x35ab8] = 0xfb;

            romData[0x33e6d] = romData[0x33e6e] = romData[0x33e6f] = 0xea;
            romData[0x317a9] = romData[0x317aa] = romData[0x317ab] = 0xea;
            romData[0x3f47b] = romData[0x3f47c] = romData[0x3f47d] = 0xea;
            //romData[0x33dba] = 0x01;
            //romData[0x33cdd] = 0x01;
            //romData[0x33fea] = 0x00;
            //romData[0x3f45a] = 0x01;
            //romData[0x33fc7] = 0x00;

            saveRom();
        }`

**Comment by Entroper** [comment]
Thanks a bunch for these!  I'll give em a try.

**Comment by gameboy9** [comment]
Here are some more speed hacks I ran into...

`            // Skip battle rewards/level ups popups (XP/Gold/levels are still actually awarded, it's just not announced)
            // Monsters perished
            romData[0x2db2c] = romData[0x2db2d] = romData[0x2db2e] = romData[0x2db2f] = romData[0x2db30] = romData[0x2db31] = 0xea;

            // XP/Gold rewards
            romData[0x2db72] = romData[0x2db73] = romData[0x2db74] = romData[0x2db75] = romData[0x2db76] = romData[0x2db77] = 0xea;

            // Level up
            romData[0x2dd7f] = romData[0x2dd80] = romData[0x2dd81] = 0xea;

            // Stats up
            romData[0x2ddb7] = romData[0x2ddb8] = romData[0x2ddb9] = romData[0x2ddba] = romData[0x2ddbb] = romData[0x2ddbc] = romData[0x2ddbd] = romData[0x2ddbe] = romData[0x2ddbf] = 0xea;
            romData[0x2ddc2] = romData[0x2ddc3] = romData[0x2ddc4] = 0xea;
`

**Comment by Entroper** [comment]
I've done just about all the speed hacks I want, I think.  I'll still look into speeding up the level-up announcements, but the game is really fast now.  :)
