### ISSUE TITLE
Program freezes while generating

### ISSUE THREAD

**Issue by Jaylow7** [Entroper/FF1Randomizer#26]
Randomizer Version 1.0.3

Flags D9B7DBB2_Kx4oBoo
(Note this happens no matter the seed, that just happens to be the one on my copy/paste to show flags)

While trying to generate seeds with the above flags, the program will fail to generate and stop responding.

Upon further testing, this happens unless **ALL THREE** of the "enemy" shuffle options (scripts, skills/spells, status attacks) are **on**.

**Comment by Entroper** [comment]
Thanks!  Figured this one out, I just totally biffed the logic on the PURE/SOFT check.  Will fix and release 1.0.4.
