### ISSUE TITLE
1.4.3 Being Reported as a Virus

### ISSUE THREAD

**Issue by Invariel** [Entroper/FF1Randomizer#29]
Windows Defender is claiming that FF1Randomizer.exe contains Trojan:Win32/Spursint.F!cl, which is probably a bad thing.

**Comment by Entroper** [comment]
I just downloaded the .zip file, unzipped it to a fresh directory, and scanned that directory with Windows Defender.  It didn't find anything.  The trojan probably infected your copy of the randomizer after you installed it.

Thanks for the report, though.

**Comment by Invariel** [comment]
I will run a full scan of my machine tonight then, because that's still
some scary stuff.

I did run a quick scan and it didn't find anything, so that's also worrying.

Having a lot of fun with 1.4.2 though, thank you.

Signed,

Adam Michaud  (invariel@gmail.com)

Everybody has a story...
