### ISSUE TITLE
No install instructions 

### ISSUE THREAD

**Issue by cconrad14** [Entroper/FF1Randomizer#30]
The instructions don't give any insight how to tie this with an emulator.

I have Jnes 1.0 and can't target the zip from this repo since there isn't a .rom file. What am I missing?

**Comment by bedmonds** [comment]
It's a stand-alone program that requires an FF1 USA rom file, which it will then use to generate a new ROM that you can load into an emulator like Jnes.

Unzip the archive somewhere and execute FF1Randomizer.exe; from then on it's fairly straightforward.

**Comment by cconrad14** [comment]
I don't see a FF1Randomizer.exe in the repo. I can't find any .exe files at all. I am supposed to compile that from source?

**Comment by Entroper** [comment]
The .exe file is in the .zip file, which you can download from the [Releases page](https://github.com/Entroper/FF1Randomizer/releases).
