### ISSUE TITLE
Bug: Infinite TENTs

### ISSUE THREAD

**Issue by Jaylow7** [Entroper/FF1Randomizer#40]
Version 1.4.9
Seed D7EBEF66
Flags r%%%AQoeoo

The Issue: At one point early in the run I bought a stack of 10 TENTs (using "buy 10"). When I went in my inventory to use one a bit later, I only had 1, and it never went away. I used that single TENT about 30 times over the course of my run.

**Comment by Entroper** [comment]
This is fixed in 1.5.0.
