### ISSUE TITLE
Ribbon picked up as weapon

### ISSUE THREAD

**Issue by BrianCumminger** [Entroper/FF1Randomizer#42]
I got a Ribbon from a chest in Earth Cave B2 and it went into my first character's weapon inventory despite my armor not being full.  This is a 1.5.1 game that I started right before 1.5.2 was released.

https://imgur.com/a/H1JzS

**Comment by sbq92** [comment]
It looks like the wrong index had its name adjusted. A recent update fixed the space after the Ribbon's name, but it seems it renamed the "Thor" hammer to "Ribbon" instead of correcting the Ribbon's name.

**Comment by Entroper** [comment]
Yeah, 0x63 and 63 aren't the same thing.  This is fixed for 1.5.3.  :)
