### ISSUE TITLE
1.6.1 binary release is flagged as virus by Windows Defender

### ISSUE THREAD

**Issue by cpetosky** [Entroper/FF1Randomizer#64]
Haven't had this issue with earlier versions. Might just be me but making an issue just in case.

OS: Windows 10 Pro v1703 build 15063.786

Can't launch "FF1Randomizer.exe" from "FF1Randomizer.zip" from release v1.6.1 (c81893f) on the releases page. Defender flags it as a virus, prevents launching it, and shortly after automatically deletes it.

v1.6 also has this problem.

v1.5 prompts me to install the .NET runtime and isn't deleted by Defender outright. Possible this issue is related to the new DLL linking you're using?

**Comment by Entroper** [comment]
I've seen this before, unforunately there isn't anything I can do about it.  This is an issue for many independent software developers.  Antivirus software sucks, it uses bad heuristics to guess at what's a virus and what isn't.
