### ISSUE TITLE
FF1 Conveniences

### ISSUE THREAD

**Issue by Entroper** [Entroper/FF1Randomizer#8]
Fixing these things will just make the game a little easier or faster to play.
- [x] Allow buying multiple items at once
- [x] B-button dash
- [x] Eliminate, move, or anchor NPCs that get in the way often, or remove bottlenecks from the maps themselves
- [x] Default Message Speed 8

**Comment by Entroper** [comment]
All the map movement stuff is in bank 0F.  StartMapMove and move_speed.  Shop stuff is in 0E, EnterShop_Item.

**Comment by RenaKunisaki** [comment]
What about saving menu cursor positions? If you want to cast heal spells several times outside of battle you have to re-select the spell and character every time. Same applies to buying/using items and managing weapons/armor IIRC.

**Comment by Entroper** [comment]
Ideally we could stay on the character selection screen after healing.  So you can just mash A on the character until he's healed, and move on to the next character.  But then you need to keep track of how many potions or spell charges are left.  It's a challenge for someone better at 6502 than me.  :)
