### ISSUE TITLE
Shuffle unrunnable encounters

### ISSUE THREAD

**Issue by Entroper** [Entroper/FF1Randomizer#99]
Also tell the player when an encounter is unrunnable, otherwise this is totally unfair.

**Comment by latzio** [comment]
I have a pending patch for this based on top of tartopan's flag refactor. It doesn't yet include any of the battle formations shared with fiends (in particular the wzsahag/rsahag and irongol battles which will remain unrunnable for now)
If there's a painless way to move those to other encounters it'll be doable but that requires finding another formation with the appropriate palettes and enemy sizes available which might not be feasible.
